### ISSUE TITLE
Add optional unit arguments to subroutines so that they can write to files

### ISSUE THREAD

**Issue by Beliavsky** [zoziha/display#1]
I suggest adding optional file unit arguments to subroutines so that they can write to files. If the unit argument is omitted, you can set it to output_unit from iso_fortran_env.

**Comment by zoziha** [comment]
Yes, the interface already supports the optional UNIT argument, as shown in the example.

https://github.com/zoziha/display/blob/7f4d2b866a39d6a0825f05bb5137db1550149a78/src/display.F90#L86

https://github.com/zoziha/display/blob/7f4d2b866a39d6a0825f05bb5137db1550149a78/example/example_display.f90#L9

**Comment by Beliavsky** [comment]
Should have looked, sorry. Thanks.
